name: Deploy to Firebase Hosting on PR
on: pull_request
jobs:
  build_and_preview:
    if: '${{ github.event.pull_request.head.repo.full_name == github.repository }}'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: npm ci && npm run build
        env:
          VITE_RAZORPAY_KEY: ${{ secrets.VITE_RAZORPAY_KEY }}   
          VITE_RAZORPAY_KEY_SECRET: ${{ secrets.VITE_RAZORPAY_KEY_SECRET }}  
      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'  # GitHub token
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_MYCOMMERCE_30045 }}'
          projectId: mycommerce-30045
